version: '3.8'

services:
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]

  configSrv_secondary_1:
    image: mongo:latest
    container_name: configSrv_secondary_1
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - config-data-secondary-1:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]

  configSrv_secondary_2:
    image: mongo:latest
    container_name: configSrv_secondary_2
    restart: always
    ports:
      - "27037:27017"
    volumes:
      - config-data-secondary-2:/data/configdb
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]

  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]

  shard1_secondary_1:
    image: mongo:latest
    container_name: shard1_secondary_1
    restart: always
    ports:
      - "27028:27018"
    volumes:
      - shard1-data-secondary-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]

  shard1_secondary_2:
    image: mongo:latest
    container_name: shard1_secondary_2
    restart: always
    ports:
      - "27038:27018"
    volumes:
      - shard1-data-secondary-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]

  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]

  shard2_secondary_1:
    image: mongo:latest
    container_name: shard2_secondary_1
    restart: always
    ports:
      - "27029:27019"
    volumes:
      - shard2-data-secondary-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]

  shard2_secondary_2:
    image: mongo:latest
    container_name: shard2_secondary_2
    restart: always
    ports:
      - "27039:27019"
    volumes:
      - shard2-data-secondary-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    depends_on:
      - configSrv
      - shard1
      - shard2
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
      - redis
    ports:
      - 8080:8080
    environment:
      #MONGODB_URL: "mongodb://mongos_router"
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  config-data:
  config-data-secondary-1:
  config-data-secondary-2:
  shard1-data:
  shard1-data-secondary-1:
  shard1-data-secondary-2:
  shard2-data:
  shard2-data-secondary-1:
  shard2-data-secondary-2:
  redis-data:
